name: nvtop
version: git
summary: Nvtop stands for NVidia TOP
description: |
  Nvtop stands for NVidia TOP, a (h)top like task monitor for NVIDIA GPUs

grade: devel
confinement: devmode
base: core18

architectures:
  - build-on: amd64

apps: 
  nvtop:
    command: $SNAP/usr/nvtop
    plugs:
      - home
      - hardware-observe
      - opengl
      - system-observe

parts:
  nvtop:
    source: https://github.com/Syllo/nvtop
    source-type: git
    plugin: cmake
#    configflags:
#      - --prefix=/usr
#    build-environment:
#      - DNVML_RETRIEVE_HEADER_ONLINE=True
#      - DCMAKE_INSTALL_PREFIX=/usr
      
    build-packages:
      - libncurses-dev
      - libncursesw5-dev
      
    stage-packages:
      - libncurses-dev
      - libncursesw5-dev
